### ISSUE TITLE
How to fit a large dataset? Out of memory.

### ISSUE THREAD

**Issue by skanskan** [JuliaStats/MixedModels.jl#160]
I would like to fit a logistic model a little bit more complex than this one to a dataset with 2 million rows where some combinations of the variables happen very  rarely. 

`fit(GeneralizedLinearMixedModel, @formula(y ~ 1 + x + w + z + sex + group + (1 | id) + (1|city)), df, Bernoulli())`

I was also trying to fit just a sample of the data on a computer with 16GB of RAM but I've only been able to do it with samples up to 50000 rows, it exhausts all the memory, if I try with a larger dataset it takes forever or crashes.

Is there any option to improve this situation and get to do it with the whole dataset?
As a last resort I would use a huge swap file but it would be very slow.

**Comment by Nosferican** [comment]
@dmbates, currently MixedModels only supports in-memory, no?

**Comment by palday** [comment]
@skanskan What are the predictors? Are `x`,`y`,`z` categorical or continuous? How many levels are there in `group`, `id` and `city`? 

(Also, I'm assuming it's just for anonymizing your formula a bit, you have `y` on both sides of the formula.)

**Comment by skanskan** [comment]
In my example:
x, w and z are continuous,
sex, group, id and city are categorical.

(It was a typo, the y it's only on the left side)

**Comment by palday** [comment]
And how many levels of group, id and city? I'm trying to figure out how big and sparse the design matrix is.

**Comment by skanskan** [comment]
I haven't worked on that analysis for a long time.
The problem here is the ID, the patient's identifier.
My dataset contains 500000 people (ID), and for each of them I have around 10 measures of each variable. (Some only have one).
City can take 30 possible values. 
Sex 2.
And group 5.
The other variables can be the age, the year, the weight and the blood pressure.

**Comment by palday** [comment]
I'm working on a similar example, but another piece of useful information would be whether the memory issue occurs when constructing or fitting the model. Can you check whether constructing the model works (with the current release version)?

```julia 
model = GeneralizedLinearMixedModel(@formula(y ~ 1 + x + w + z + sex + group + (1 | id) + (1|city)), df, Bernoulli())
```

If that works, then try fitting:
```julia
fit!(model)
```

Since January, there have been a few changes in the internal representation that might (but probably won't :/ ) make a difference here.

**Comment by palday** [comment]
I've tried creating my own example to see where the issue arises (and making later testing easier). The total number of observations isn't a huge issue, but the number of the random effects does matter (which makes sense given the internal representation of these things):

```julia
using Random, DataFrames, MixedModels
gendata(n::Int, nID::Int) = gendata(MersenneTwister(42), n, nID)

function gendata(rng::AbstractRNG, n::Int, nID::Int)
    df = DataFrame(y = ones(n),
                   w = rand(rng, n),
                   x = rand(rng, n),
                   z = rand(rng, n),
                   sex = map(x -> randstring(rng,"mf",1),1:n),
                   group = rand(rng, 1:5, n),
                   ID = rand(rng, 1:nID, n),
                   city = rand(rng, 1:30, n))
    df = categorical!(df, [:sex, :group, :ID, :city])

    # join and non in-place operations aren't the most memory efficient
    # but it works well enough for an example
    uID = DataFrame(ID = unique(df.ID),
                    u = length(unique(df.ID)))

    df = join(df, uID, on=:ID)
    # set all betas for continous to 1 and normal(0,1) residuals
    # group isn't further specified, so it's just noise
    df.y = df.w + df.x + df.z + (df.sex .== "m") + df.u + randn(rng,n)

    for cc in unique(df.city)
        df[df.city .== cc, :y] = df[df.city .== cc, :y] .+ randn(rng)
    end

    df
end

df = gendata(100,10);
warmup = LinearMixedModel(@formula(y ~ 1 + x + w + z + sex + group + (1 | ID) + (1|city)), df);
fit!(warmup);
```

This all works well even for 2 million observations and a non trivial number of levels of ID:

```julia
julia> @time df = gendata(1000,10);
  0.002022 seconds (10.51 k allocations: 1.139 MiB)

julia> @time msmall = LinearMixedModel(@formula(y ~ 1 + x + w + z + sex + group + (1 | ID) + (1|city)), df);
  0.894582 seconds (1.19 M allocations: 62.398 MiB, 3.17% gc time)

julia> @time fit!(msmall);
  0.002090 seconds (2.08 k allocations: 53.328 KiB)

julia> @time df = gendata(1000000,1000);
  1.776882 seconds (9.00 M allocations: 737.574 MiB, 45.54% gc time)

julia> @time mbig = LinearMixedModel(@formula(y ~ 1 + x + w + z + sex + group + (1 | ID) + (1|city)), df);
  1.989211 seconds (1.19 M allocations: 563.469 MiB, 24.67% gc time)

julia> @time fit!(mbig);
  0.112918 seconds (3.69 k allocations: 93.453 KiB)

julia> @time df = gendata(2000000,5000);
  4.193468 seconds (18.02 M allocations: 1.425 GiB, 49.34% gc time)

julia> @time mhuge = LinearMixedModel(@formula(y ~ 1 + x + w + z + sex + group + (1 | ID) + (1|city)), df);
  3.610134 seconds (1.20 M allocations: 1.387 GiB, 33.47% gc time)

julia> @time fit!(mhuge);
  0.179006 seconds (3.57 k allocations: 90.328 KiB)
```
But things break down if we crank up the number of levels:

```julia 
julia> @time df = gendata(2000000, 25000);  3.928245 seconds (18.08 M allocations: 1.448 GiB, 46.91% gc time)

julia> @time mhuge = LinearMixedModel(@formula(y ~ 1 + x + w + z + sex + group + (1 | ID) + (1|city)), df);
240.145810 seconds (1.24 M allocations: 10.361 GiB, 8.90% gc time)

julia> @time fit!(mhuge)
  1.413340 seconds (3.09 k allocations: 79.141 KiB)

julia> @time df = gendata(2000000, 50000);  9.656339 seconds (18.15 M allocations: 1.471 GiB, 19.11% gc time)

julia> @time mhuge = LinearMixedModel(@formula(y ~ 1 + x + w + z + sex + group + (1 | ID) + (1|city)), df);
ERROR: OutOfMemoryError()
```

Note that it's the construction of the model that is the difficult bit here -- we can solve for two scalar random effects quite quickly once we have the right representation, but getting that requires a bit of overhead.

**Comment by skanskan** [comment]
What if you nest   (1 | city/id)  as in lme4?  
That way is faster in R and needs less memory.

**Comment by skanskan** [comment]
Thanks, 
Next week I'll try ypur example and with my data.
What if you nest the random effects  (1|city/ID), in R is faster and needs less memory. (I know is not exactly the same model).

**Comment by palday** [comment]
The nesting syntax isn't currently supported in MixedModels. It also isn't strictly necessary in lme4 or mixed models (see #149) as long as the labels for ID are unique (i.e. don't repeat across cities if individuals don't move across cities). But brings me to the next point: do individuals move across cities? This actually makes a huge difference in the sparsity of the random effects (nested vs. partially crossed).

**Comment by skanskan** [comment]
> The nesting syntax isn't currently supported in MixedModels. It also isn't strictly necessary in lme4 or mixed models (see #149) as long as the labels for ID are unique (i.e. don't repeat across cities if individuals don't move across cities). But brings me to the next point: do individuals move across cities? This actually makes a huge difference in the sparsity of the random effects (nested vs. partially crossed).

Most of them not.  
In fact in my analysis I want to show how different are the results whether you consider one model or the other.

**Comment by palday** [comment]
I've updated the `gendata` example to have strict nesting (the previous example was partially crossed):   [talldatasim.jl](https://gist.github.com/palday/0ce66d7a2c404a129430fa4a848d6518)

**Comment by skanskan** [comment]
@palday, when I try @time df = gendata(2000000,200000); I get the error 'ERROR: DimensionMismatch("column length 199990 for column(s) ID, and is incompatible with column length 200000 for column(s) u")'
Does it have to do with the out of memory problem or a 199990 limitation for the number of columns?

**Comment by palday** [comment]
No, it's related to the way the data are generated.  `gendata` isn't terribly optimized and uses a rather naive way of drawing random IDs, which can lead to problems when the number of IDs is large, especially relative to the number of observations. Basically, there's no guarantee that enough unique IDs will be generated because IDs are just draws from the set of unique IDs. For now, you can see if you're 'luckier' when using a different random seed (with `gendata(MersenneTwister(some_number_but_not_42), 2000000, 200000)`.
