### ISSUE TITLE
How to test significance of random effects

### ISSUE THREAD

**Issue by marynavickt** [JuliaStats/MixedModels.jl#168]
Is it possible to perform test of significance for RE obtained by ranef function? Or maybe just calculate confidence intervals for each RE coefficient?

**Comment by dmbates** [comment]
It is not clear what such hypothesis tests or confidence intervals would be.  Strictly speaking they don't exist because the random effects are not parameters.

It is possible to form prediction intervals but the calculation is rather complicated in all but the simplest cases.  The condVar function returns the conditional variances of the random effects but only for cases with a single, scalar random-effects term.

**Comment by marynavickt** [comment]
Would that be so wrong if the calculation for multiple random-effects terms looks like this:

'll = diag(model.trms[1].Λ)'
ld = diag(model.L.data[Block(1, 1)])

ll represents models terms (in my case N = 5).
Every 5 elements of ld correspond to 5 elements in ll (FE are the same), so we probably could replicate ll k times (where k = length(ld)/length(ll)) and concatenate the results. That way ll becomes a vector with the same size as ld.
In the end what I wanted to do is ll/ld*varest(model).

**Comment by dmbates** [comment]
How many random-effects terms do you have?  If you just have one term but it is a vector-valued term I should be able to cook something up for you.

**Comment by marynavickt** [comment]
My formula looks like y~x1+x2+...+ (1|r1)+(x1|r1)+(x2|r1)+...+(x5|r1) like this  , so I suppose it's one vector-valued term. It would be really helpful if you could come up with some solution for this case.

**Comment by dmbates** [comment]
You don't want to use that formula.  You need to write it as
```
y ~ 1+x1+x2+...+ (1|r1) + (0+x1|r1) + (0+x2|r1) + ... + (0+x5|r1)
```
otherwise there are 6 different instances of a random intercept by levels of `r1`

**Comment by marynavickt** [comment]
Sorry, my bad, forgot about 0's. That's the formula
`y ~ 1+x1+x2+...+ (1|r1) + (0+x1|r1) + (0+x2|r1) + ... + (0+x5|r1)`

**Comment by dmbates** [comment]
Could you send me the output from `describeblocks` applied to your model?  I want to know if the (1,1) block is `Diagonal` or `UniformBlockDiagonal`

**Comment by marynavickt** [comment]
1,1: UniformBlockDiagonal{Float64} (10270, 10270) UniformBlockDiagonal{Float64}
2,1: Array{Float64,2} (1077, 10270) Array{Float64,2}
2,2: Array{Float64,2} (1077, 1077) Array{Float64,2}
3,1: Array{Float64,2} (1, 10270) Array{Float64,2}
3,2: Array{Float64,2} (1, 1077) Array{Float64,2}
3,3: Array{Float64,2} (1, 1) Array{Float64,2}

**Comment by dmbates** [comment]
Okay, that is good to know.  What is
```julia
size(m.A[Block(1,1)].data))
```

It seems to me that from that fact that you have 1077 fixed-effects parameters you probably have very large blocks in `m.A[Block(1,1)]` and that is causing the problems.

**Comment by marynavickt** [comment]
[[1]]
[1] 5
[[2]]
[1] 5
[[3]]
[1] 201
attr(,"class")
[1] "JuliaTuple"

**Comment by dmbates** [comment]
That looks like R output.  Can you give me the version from Julia?

Those numbers don't make sense to me because you should have the first two dimensions equal (as they are here) and the product of the first and third dimensions equal to the first dimension of the overall matrix - 10270 in this case.  But 5 * 201 = 1005

**Comment by marynavickt** [comment]
You're right, was testing the model on a different dataset.
Output  5,5,2054

**Comment by dmbates** [comment]
Is `first(m.L.data[Block(1,1)].facevec)` diagonal?

**Comment by marynavickt** [comment]
Looks like this
    1    0       0.000000      0.00000       0.0000
    0    1       0.000000      0.00000       0.0000
    0    0      2.552594      57.90547      475.6131
    0    0      22.684949    33.90157     13453.6630
    0    0     186.325357   272.16679    10.0804

**Comment by dmbates** [comment]
With commit https://github.com/dmbates/MixedModels.jl/commit/30fcb6eed49710cf849202d6288c5314422626e5 I think the `condVar` should work on your model.  Can you check for me if the values make sense to you?  It returns a `UniformBlockDiagonal` matrix with the variances on the diagonal and covariances off the diagonal.   Random effects corresponding to different levels of the grouping factor are uncorrelated so in your case this matrix will consist of 2054 symmetric diagonal blocks of size 5 by 5.

**Comment by marynavickt** [comment]
Yep, got the results from condVar for my model. Could you explain what would be the right way for constructing prediction intervals?

**Comment by kleinschmidt** [comment]
BTW, with #207 you'll be able to express that formula as ` y ~ 1+x1+x2+...+ zerocorr(1+x1+x2+...|r1)`

**Comment by palday** [comment]
Prediction intervals are essentially ranef ±1.96 * sqrt(conditional variance), as currently used in [MixedModelsMakie to construct caterpillar plots](https://github.com/palday/MixedModelsMakie.jl/blob/c624531ee9c560818c85a1f166bae2297958345a/src/caterpillar.jl#L66).
