### ISSUE TITLE
No predict method for GeneralizedLinearMixedModels

### ISSUE THREAD

**Issue by amillscampisi** [JuliaStats/MixedModels.jl#175]
I am estimating a glm similar to the VerbAgg example in the documentation. The predict method doesn't support GeneralizedLinearMixedModel. I was able to replicate the error using the VerbAgg example.

```
using DataFrames, MixedModels, RData

const dat = Dict(Symbol(k)=>v for (k,v) in 
    load(joinpath(dirname(pathof(MixedModels)), "..", "test", "dat.rda")));

verbaggform = @formula(r2 ~ 1 + a + g + b + s + m + (1|id) + (1|item));

gm1 = fit(GeneralizedLinearMixedModel, verbaggform, dat[:VerbAgg], Bernoulli())

predict(gm1, dat[:VerbAgg])
```

And I get the following error:

```
MethodError: no method matching predict(::GeneralizedLinearMixedModel{Float64}, ::DataFrame)
Closest candidates are:
  predict(!Matched::StatsModels.DataFrameRegressionModel{T,T} where T, ::AbstractDataFrame; kwargs...) where T at /home/ec2-user/.julia/packages/StatsModels/pBxdt/src/statsmodel.jl:118
  predict(!Matched::StatsModels.DataFrameRegressionModel, ::Any...; kwargs...) at /home/ec2-user/.julia/packages/StatsModels/pBxdt/src/statsmodel.jl:28
  predict(::GeneralizedLinearMixedModel) at /home/ec2-user/.julia/packages/MixedModels/YIBOE/src/PIRLS.jl:134
  ...

Stacktrace:
 [1] top-level scope at In[8]:1
```

**Comment by amillscampisi** [comment]
I've been familiarizing myself with home Statsbase works. I think I understand how I can add a predict method. If Prof Bates can give me a few details on how it wants it implemented, I can try to implement it.

**Comment by ClimateNexus** [comment]
Hi there.  any update on a predict function?  Looking to transition our regression code from lme4-R to Julia given the speed gains.  Thanks.

**Comment by dmbates** [comment]
The first thing to establish is what a predict method should do with the random effects.  If you want predictions for previously unobserved values of the grouping factor then it is reasonably straightforward to just use the fixed-effects estimates and set all the random effects to zero.  That provides the mean response at the values of the covariates.  Getting the prediction intervals is a bit trickier because you need to take into account the variation in the unknown random effects.

If you are trying to predict at observed values of the grouping factors then you need to select the appropriate random effects vector(s) if you want even the mean response.

Which are you trying to do?

**Comment by amillscampisi** [comment]
In my case it is both. I built a discrete time hazard model with repeated events. To control for the unbalanced panel, each individual has a mixed effect. I need to validate the model, so I set up a train-test-test split. Each group served a different purpose:

Group 1: A training group that included 1/3 of the population and all their observations. This group will be used for in-sample validation. 

Group 2: A training group that included 1/3 of the population, but only half their observations. I was going to use this population to do an out-of-time validation of the mixed effect terms, i.e., how well does the model predict the next event, assuming it has a mixed effect term for the individual. 

Group 3: The third group is a fully out-of-sample test group. It contains the remaining 1/3 of the population and all their observations. It measures the model's performance when there is no mixed-effect term.

**Comment by andyreagan** [comment]
At one time, I wrote some `predict` methods that worked for my own use case, but were not suitable for inclusion into the codebase as-is #113. 

I'd be happy to revive these (with a fresh PR) if we can all agree up front on how a `predict` function for GLMM _should_ handle the random effects. It will be much easier to do correctly since #114 has been fixed.

**Comment by jkrumbiegel** [comment]
I want to use a GLMM to estimate parameters for psychometric curves, and I want to generate an average psychometric curve for each of the conditions in my experiment. The participants are the random variable, so in my understanding to generate an average curve for each combination of conditions, the random effect of the participants would just be set to zero.

How do I create a prediction like that? I don't understand the internals of this package well enough to create it myself. I know I need to plug the fixed effects coefficients into a matrix, multiply with my variables and apply the link function, but I want to use the formula object that I already have, not write it out manually..

**Comment by jerlich** [comment]
This function would be very useful! Ideally there would be an option of whether or not to use the random effects.

**Comment by palday** [comment]
This is non trivial to implement -- there's a lot of "not hard, but very effortful and tedious" parts as well as deeper considerations about how to design the interface (e.g. how to handle the random effects? what about new levels of the grouping variable?, etc.).  There are a few more pressing issues we're working on, which will also work as stepping stones for this functionality (e.g. `simulate!` for GLMMs, which will then open up `parametricbootstrap` support for GLMMs). In other words: sorry for the delay, but thanks for commenting -- it does help us to know what the users' priorities are.

While we work on this, I would recommend using [JellyMe4](https://github.com/palday/JellyMe4.jl) to shove the models over into R and using the `predict` machinery on that side (assuming of course that you have some familiarity with R).

**Comment by palday** [comment]
Note to self, quoting [an idea for `(g)lmer`](https://hypatia.math.ethz.ch/pipermail/r-sig-mixed-models/2020q4/029020.html) from @bbolker :
>it would certainly make sense that you might want these cases to be NA rather than predicted at the population level.  In hindsight it might have been a good idea to set this up as new.re.levels allowing the options c("population","fail", "exclude", "omit").
