### ISSUE TITLE
Comparing models (Equivalent to `anova` in R)

### ISSUE THREAD

**Issue by Tokazama** [JuliaStats/MixedModels.jl#182]
I apologize if I missed this in the manual, but is there a method to compare models similar to `anova` in R?

**Comment by Tokazama** [comment]
I found what I was looking for under `MixedModels.likelihoodratiotest`. I didn't see any documentation on this, so is it intentionally not exported or included on the docs?

**Comment by nalimilan** [comment]
Note that it's been requested many times that we add `likelihoodratiotest` (or `lrtest`) to StatsBase, similar to how `ftest` is implemented in GLM. The definition could work for many different kinds of models, including MixedModels.

**Comment by Tokazama** [comment]
Implementing it would be almost as simple as copying and pasting the code here. Is there a reason that both `ftest` and `lrtest` haven't made it into StatsBase?

**Comment by nalimilan** [comment]
`ftest` only applies to linear models, so it doesn't make a lot of sense to have it in StatsBase. But a PR to implement `lrtest` in StatsBase based on the `ftest` code would be welcome.

**Comment by palday** [comment]
Related: [Wald-tests in Julia](https://natsiopoulos.netlify.com/post/wald-test-julia/wald-test-julia/).

**Comment by Nosferican** [comment]
I think that should probably be a simple extension of the StatisticalModel API... using `vcov`, `coef`, `dof_residual`, `hasintercept`, `islinear`... while it could provide a dist (F-Dist / Chi2), a statistic, and say the p-value. The nice aspect of having it as an extension is to focus on nice ways to express the linear restrictions. For example, based on the term names, range, term fam, matrix, etc.

**Comment by palday** [comment]
Closing because we have `MixedModels.likelihoodratiotest`. If `lrtest` lands in StatsModels, then we'll add an appropriate method.
