### ISSUE TITLE
a different wts argument issue / no impact on estimates

### ISSUE THREAD

**Issue by jbrj** [JuliaStats/MixedModels.jl#194]
I was unable to find much documentation on wts, but did read through related topics here.  I am seeing in some cases that the wts argument does not appear to behave as expected - weights have no impact on the reported estimates.  I put together a simple example to show the difference in outputs between lmer and MixedModels for both REML and ML.

-----
#### mm/lmm  Setup (Julia)
-----
```
aDf = DataFrame(a = [1.55945122,0.004391538,0.005554163,-0.173029772,4.586284429,0.259493671,-0.091735715,5.546487603,0.457734831,-0.030169602], b = [0.24520519,0.080624178,0.228083467,0.2471453,0.398994279,0.037213859,0.102144973,0.241380251,0.206570975,0.15980803], c = ["H","F","K","P","P","P","D","M","I","D"],  w1 = [20,40,35,12,29,25,65,105,30,75], w2 = [0.04587156,0.091743119,0.080275229,0.027522936,0.066513761,0.05733945,0.149082569,0.240825688,0.068807339,0.172018349])
aDf.c = CategoricalArray(aDf.c)
```
-----
#### mm/lmm  ML Results
-----
```
mod1 = fit(MixedModel, @formula(a ~ 1 + b + (1|c)), aDf, wts = Array(aDf.w1))
```
Linear mixed model fit by maximum likelihood
 a ~ 1 + b + (1 | c)
     logLik         -2 logLik       AIC            BIC
 -0.6768517  1.3537034  9.3537034 10.5640437

Variance components:
              Column    Variance  Std.Dev.
 c        (Intercept)  0.0000000 0.0000000
 Residual              2.4188698 1.5552716
 Number of obs: 10; levels of grouping factors: 7

 Fixed-effects parameters:
             Estimate  Std.Error   z value  P(>|z|)
(Intercept)  -1.24783    1.08491  -1.15016   0.2501
      b           12.6351     4.96634   2.54415   0.0110

```
mod2 = fit(MixedModel, @formula(a ~ 1 + b + (1|c)), aDf, wts = Array(aDf.w2))
```
Linear mixed model fit by maximum likelihood
 a ~ 1 + b + (1 | c)
       logLik      -2 logLik        AIC            BIC
 -31.065063  62.130126  70.130126  71.340466

Variance components:
              Column    Variance  Std.Dev.
 c        (Intercept)  0.0000000 0.0000000
 Residual              2.4188698 1.5552716
 Number of obs: 10; levels of grouping factors: 7

  Fixed-effects parameters:
             Estimate  Std.Error   z value  P(>|z|)
(Intercept)  -1.24783    1.08491  -1.15016   0.2501
      b           12.6351     4.96634   2.54415   0.0110

```
mod3 = fit(MixedModel, @formula(a ~ 1 + b + (1|c)), aDf)
```
Linear mixed model fit by maximum likelihood
 a ~ 1 + b + (1 | c)
      logLik       -2 logLik        AIC            BIC
 -18.605887  37.211775  45.211775  46.422115

Variance components:
              Column    Variance  Std.Dev.
 c        (Intercept)  0.0000000 0.0000000
 Residual              2.4188698 1.5552716
 Number of obs: 10; levels of grouping factors: 7

  Fixed-effects parameters:
                     Estimate  Std.Error   z value  P(>|z|)
(Intercept)  -1.24783    1.08491  -1.15016   0.2501
      b           12.6351     4.96634   2.54415   0.0110

-----
#### mm/lmm  RML Results
-----
```
mod4 = fit!(LinearMixedModel(@formula(a ~ 1 + b + (1|c)), aDf), REML = true)
```
Linear mixed model fit by REML
 a ~ 1 + b + (1 | c)
 REML criterion at convergence: 31.5350887187607

Variance components:
              Column    Variance  Std.Dev.
 c        (Intercept)  0.0000000 0.0000000
 Residual              3.0235872 1.7388465
 Number of obs: 10; levels of grouping factors: 7

  Fixed-effects parameters
                    Estimate  Std.Error   z value  P(>|z|)
(Intercept)  -1.24783    1.21297  -1.02874   0.3036
      b           12.6351     5.55253   2.27556   0.0229

```
mod5 = fit!(LinearMixedModel(@formula(a ~ 1 + b + (1|c)), aDf, wts = Array(aDf.w1)), REML = true)
```
Linear mixed model fit by REML
 a ~ 1 + b + (1 | c)
 REML criterion at convergence: -4.322982490290936

Variance components:
              Column    Variance  Std.Dev.
 c        (Intercept)  0.0000000 0.0000000
 Residual              3.0235872 1.7388465
 Number of obs: 10; levels of grouping factors: 7

  Fixed-effects parameters:
             Estimate  Std.Error   z value  P(>|z|)
(Intercept)  -1.24783    1.21297  -1.02874   0.3036
      b           12.6351     5.55253   2.27556   0.0229

-----
#### lmer Setup (R)
-----
```
x.dt <- data.table(c(1.55945122,0.004391538,0.005554163,-0.173029772,4.586284429,0.259493671,-0.091735715,5.546487603,0.457734831,-0.030169602), c(0.24520519,0.080624178,0.228083467,0.2471453,0.398994279,0.037213859,0.102144973,0.241380251,0.206570975,0.15980803), 
                   c("H","F","K","P","P","P","D","M","I","D"),  c(20,40,35,12,29,25,65,105,30,75), c(0.04587156,0.091743119,0.080275229,0.027522936,0.066513761,0.05733945,0.149082569,0.240825688,0.068807339,0.172018349))
colnames(x.dt) <- c('a', 'b', 'c', 'w1', 'w2')
x.dt$c <- as.factor(x.dt$c)
r1 <- lmer(a ~ 1 + b + (1|c), data = x.dt, weights = w1, REML = FALSE)
r2 <- lmer(a ~ 1 + b + (1|c), data = x.dt, weights = w2, REML = FALSE)
r3 <- lmer(a ~ 1 + b + (1|c), data = x.dt, REML = FALSE)
r4 <- lmer(a ~ 1 + b + (1|c), data = x.dt, REML = TRUE)
r5 <- lmer(a ~ 1 + b + (1|c), data = x.dt, weights = w1, REML = TRUE)
```

-----
#### lmer ML Results
-----
```
r1
```
Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: a ~ 1 + b + (1 | c)
   Data: x.dt
Weights: w1
     AIC         BIC       logLik   deviance df.resid 
 45.7261  46.9364 -18.8630  37.7261        6 
Random effects:
 Groups   Name        Std.Dev.
 c        (Intercept) 1.553   
 Residual             5.261   
Number of obs: 10, groups:  c, 7
Fixed Effects:
(Intercept)            b  
    -0.8573      11.8732  

```
r2
```
Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: a ~ 1 + b + (1 | c)
   Data: x.dt
Weights: w2
     AIC         BIC       logLik deviance df.resid 
 45.7261  46.9364 -18.8630  37.7261        6 
Random effects:
 Groups   Name        Std.Dev.
 c        (Intercept) 1.5528  
 Residual             0.2519  
Number of obs: 10, groups:  c, 7
Fixed Effects:
(Intercept)            b  
    -0.8573      11.8732  

```
r3
```
Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: a ~ 1 + b + (1 | c)
   Data: x.dt
     AIC         BIC       logLik   deviance df.resid 
 45.2118  46.4221 -18.6059  37.2118        6 
Random effects:
 Groups   Name        Std.Dev.
 c        (Intercept) 0.000   
 Residual             1.555   
Number of obs: 10, groups:  c, 7
Fixed Effects:
(Intercept)            b  
     -1.248       12.635  

-----
#### lmer REML Results
-----
```
r4
```
Linear mixed model fit by REML ['lmerMod']
Formula: a ~ 1 + b + (1 | c)
   Data: x.dt
REML criterion at convergence: 31.5351
Random effects:
 Groups   Name        Std.Dev.
 c        (Intercept) 0.000   
 Residual             1.739   
Number of obs: 10, groups:  c, 7
Fixed Effects:
(Intercept)            b  
     -1.248       12.635  

```
r5
```
Linear mixed model fit by REML ['lmerMod']
Formula: a ~ 1 + b + (1 | c)
   Data: x.dt
Weights: w1
REML criterion at convergence: 32.0785
Random effects:
 Groups   Name        Std.Dev.
 c        (Intercept) 1.686   
 Residual             6.106   
Number of obs: 10, groups:  c, 7
Fixed Effects:
(Intercept)            b  
    -0.8668      11.9763  

I'm new to Julia (and Git), so apologies if my julia code is overly verbose with the casts. It doesn't appear they're needed, but other examples include them. Likewise, apologies if the provided information/'wall of text' is overboard.

Disclaimer aside, is there something I'm missing on how to properly utilize wts with MixedModels? The wts argument does appear to affect the log-likelihood/convergence criterion, but has no effect on the estimates.  The changes in llk/cc when using wts in MixedModels don't align with lmer, but they are different than not using a wts argument.  

The log-likelihood/AIC for MixedModels also vary on whether w1 or w2 is used for wts, where w2 is a scaled vector resulting from w1 / sum(w1).  There are no differences in the log-likelihood/AIC/estimates in lmer whether w1 or w2 are used.

Version info: 
- MixedModels v2.1.1
- Julia version v1.0.3

If there's anything else I can supply that would be helpful, please let me know.

**Comment by Nosferican** [comment]
I can confirm the behavior,
MixedModels.jl,
```
using DataFrames, MixedModels

data = DataFrame(a = [1.55945122,0.004391538,0.005554163,-0.173029772,4.586284429,0.259493671,-0.091735715,5.546487603,0.457734831,-0.030169602],
                 b = [0.24520519,0.080624178,0.228083467,0.2471453,0.398994279,0.037213859,0.102144973,0.241380251,0.206570975,0.15980803],
                 c = categorical(["H","F","K","P","P","P","D","M","I","D"]),
                 w1 = [20,40,35,12,29,25,65,105,30,75],
                 w2 = [0.04587156,0.091743119,0.080275229,0.027522936,0.066513761,0.05733945,0.149082569,0.240825688,0.068807339,0.172018349])
mod1 = fit(MixedModel, @formula(a ~ 1 + b + (1|c)), data)
mod2 = fit(MixedModel, @formula(a ~ 1 + b + (1|c)), data, wts = aDf.w1)
mod3 = fit(MixedModel, @formula(a ~ 1 + b + (1|c)), data, wts = aDf.w2)
mod4 = fit(MixedModel, @formula(a ~ 1 + b + (1|c)), data, REML = true)
mod5 = fit(MixedModel, @formula(a ~ 1 + b + (1|c)), data, wts = aDf.w1, REML = true)
mod6 = fit(MixedModel, @formula(a ~ 1 + b + (1|c)), data, wts = aDf.w2, REML = true)
```
and R's lme4
```
library(maditr)
library(lme4)

dat <- data.table(a = c(1.55945122,0.004391538,0.005554163,-0.173029772,4.586284429,0.259493671,-0.091735715,5.546487603,0.457734831,-0.030169602),
                   b = c(0.24520519,0.080624178,0.228083467,0.2471453,0.398994279,0.037213859,0.102144973,0.241380251,0.206570975,0.15980803),
                   c = c("H","F","K","P","P","P","D","M","I","D"),
                   w1 = c(20,40,35,12,29,25,65,105,30,75),
                   w2 = c(0.04587156,0.091743119,0.080275229,0.027522936,0.066513761,0.05733945,0.149082569,0.240825688,0.068807339,0.172018349))
mod1 <- lmer(formula = a ~ 1 + b + (1|c),
             data = dat,
             REML = FALSE)
mod2 <- lmer(formula = a ~ 1 + b + (1|c),
             data = dat,
             weights = w1,
             REML = FALSE)
mod3 <- lmer(formula = a ~ 1 + b + (1|c),
             data = dat,
             weights = w2,
             REML = FALSE)
mod4 <- lmer(formula = a ~ 1 + b + (1|c),
             data = dat)
mod5 <- lmer(formula = a ~ 1 + b + (1|c),
             data = dat,
             weights = w1)
mod6 <- lmer(formula = a ~ 1 + b + (1|c),
             data = dat,
             weights = w2)
```
Thanks for bringing this to our attention. It seems like there is a bug with the weights. We'll check on it and add this case to the test suite to make sure we test against that in the future.

**Comment by palday** [comment]
I've taken a look at this: the weights are taken into account when computing the objective (if you look, you'll see that the log likelihoods are different), but the weights aren't used when computing the fixed effect coefficients and standard errors.
