### ISSUE TITLE
Constrain fixed effects and conditional modes of random effects

### ISSUE THREAD

**Issue by binari2** [JuliaStats/MixedModels.jl#235]
How can I constrain some fixed effects and some conditional modes of random effects to be negative?  Not all, just specific effects.

**Comment by palday** [comment]
Why do you want to do this?

**Comment by dmbates** [comment]
It would be possible to use a constrained, penalized least squares optimization instead of the current penalized least squares but it would neither be easy to do nor fast.

**Comment by palday** [comment]
@dmbates That was also my intuition. I'm curious if this is an [XY problem](http://xyproblem.info/).
