### ISSUE TITLE
document fulldummy

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaStats/MixedModels.jl#255]
the `zerocorr*` functions are documented (in constructors.jmd) but `fulldummy` isn't.  Might be a  good idea to have a separate "formula extensions" page to document all the special syntax that mixed models introduces.

**Comment by kleinschmidt** [comment]
Since this came up on Zulip after merging #269, it might be good to have a docs page dedicated specifically to the various ways of controlling the variance/correlation parameters in the random effects, which would cover `zerocorr`, `fulldummy`, and the difference between `(1+x|g)` and `(1|g) + (0+x|g)`.

**Comment by palday** [comment]
If we're talking about magic .... does it make sense to have `(1|g) + (x|g)` detect the presence of an intercept and not do an implicit intercept?  Or more generally, remove redundant terms? (Maybe the latter is already caught be the normal formula handling and `amalgamate`.)

**Comment by kleinschmidt** [comment]
Yeah I noticed that when I was playing around last night.  I'd have thought that works but it doesn't for some reason, I'll have to go back and see why.  I think it's because the default intercept behavior doesn't take into account the other terms, since they're only linked by the schema...

**Comment by palday** [comment]
@kleinschmidt Do you have time/energy/capacity to do this in the next two weeks?

**Comment by kleinschmidt** [comment]
If it's blocking I can.  Ping me again in a few days...

**Comment by dmbates** [comment]
@palday @kleinschmidt Is the issue here documenting the `MixedModels.fulldummy` function or the `StatsModels.FullDummy` type?  If it is the function I can do that.

**Comment by dmbates** [comment]
Do we have a canonical example of the use of `fulldummy`, maybe the machines data?  I can create a branch with the function documentation string and can add some text to `docs/src/constructors.md` but I should incorporate an example in the docs.

**Comment by kleinschmidt** [comment]
Yes the function. But also things like zerocorr and splitting terms across multiple RES to remove correlations. Basically all the ways you can control the correlation structure you fit. 

I'm not sure about a canonical dataset but maybe whatever we have in the tests? Unless that's just made up stuff, I can't remember...
