### ISSUE TITLE
unintuitive behavior with multiple terms with same grouping factor

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaStats/MixedModels.jl#268]
Currently, if you have a formula like `y ~ 1 + (1|G) + (0+A|G)` where `A` is a categorical variable with `n` levels, then you'll generate 1 variance term for the random intercept, and `n` terms for `A`, leading to an overparametrized model.  This may not be what you want; listing these as separate terms is a way to indicate that you want to zero out the correlation terms between the random intercept and the random slopes for `A`, and you end up changing the number of variance terms (relative to the `(1+A|G)` formula).

This can be fixed by changing the way that the schema is applied.  Currently, a fresh `StatsModels.FullRank` schema is prepared for every random effect term, meaning that the `0+A` is treated as independent from the `1`.  An alternative approach would be to add yet another level of schema wrapping (which I'll prepare a PR for), which stores one `FullRank` schema for each grouping variable and applies it across multiple terms.  But this is a **breaking change** and may require changing how amalgamate works as well.  It's tested here:

https://github.com/JuliaStats/MixedModels.jl/blob/c87e8d14ef934f1c3446d7ae4c5422adae6578c5/test/pls.jl#L277-L290

**Comment by palday** [comment]
@kleinschmidt Have you had time to implement this?

**Comment by kleinschmidt** [comment]
not beyond what's in #269, which IIRC needs some love to work with `amalgamate` but maybe that's changed in the mean time?
