### ISSUE TITLE
correlation of fixed-effects

### ISSUE THREAD

**Issue by palday** [JuliaStats/MixedModels.jl#271]
Do we want to add an option for printing the correlation of fixed effects?

I would prefer to have the default printing behavior to be as it is now because nobody understands what the correlation of fixed effects actually means, but for the rare user who does, it can be useful information.

**Comment by dmbates** [comment]
I thought there was a `cor` extractor function that whould return that information but I was wrong.  The `vcov` function returns the variance-covariance matrix of the fixed-effects estimator so it is possible to work with that to create the correlation matrix.  Would you like me to do that?

If you look at the code for `vcov` in `linearmixedmodel.jl` you will see that it is built by taking a symmetric product of the `[n-1, n-1]` block of `L` so you can work directly with that block (or I can write it if you wish).
