### ISSUE TITLE
Two Interactions Causing Error

### ISSUE THREAD

**Issue by liamlundy** [JuliaStats/MixedModels.jl#284]
I'm running into a case where a model unexpectedly fails. The root of the problem has been distilled into the following example. The data is attached below the code.

The first two cases are interacted by a single variable and they both pass. The third example is interacted by both variables and fails. In all cases there are enough levels in the data for the interaction to be valid. Let me know if I am missing an issue in the data.

```julia
using StatsModels, MixedModels, CSV, DataFrames

model_ready_data = CSV.read("data.csv")
categorical!(model_ready_data, :cat1)
categorical!(model_ready_data, :cat2)

model_form = @eval StatsModels.@formula(y ~ 1 + (1 | cat1))
model = LinearMixedModel(model_form, model_ready_data)
print(MixedModels.fit!(model))

model_form = @eval StatsModels.@formula(y ~ 1 + (1 | cat2))
model = LinearMixedModel(model_form, model_ready_data)
print(MixedModels.fit!(model))

model_form = @eval StatsModels.@formula(y ~ 1 + (1 | cat2) + (1 | cat1))
model = LinearMixedModel(model_form, model_ready_data)
print(MixedModels.fit!(model))
```

[data.zip](https://github.com/JuliaStats/MixedModels.jl/files/4231541/data.zip)

Package versions:
- CSV v0.5.23
- DataFrames v0.20.0
- MixedModels v2.2.0
- StatsModels v0.6.8

**Comment by palday** [comment]
What happens when you remove the `@eval`? You should not be eval'ing a macro such as `@formula`.

One other tip: since you're using `using`, you don't have to specify `StatsModels.@formula` or `MixedModels.fit!`, you can just write `@formula` or `fit!`.

**Comment by liamlundy** [comment]
> What happens when you remove the `@eval`? You should not be eval'ing a macro such as `@formula`.
> 
> One other tip: since you're using `using`, you don't have to specify `StatsModels.@formula` or `MixedModels.fit!`, you can just write `@formula` or `fit!`.

The `@eval` is because my formal usage pattern requires me to programmatically create the formula like this:
`@eval StatsModels.@formula($lhs ~ $rhs)`. You actually HAVE to use `@eval` in cases like this to create the formula or you will get an `ArgumentError: interpolation with $ not supported in @formula.  Use @eval @formula(...) instead.` error. With increased support to building the formula using the underlying terms, I would like to move towards that, but either way that is not what is affecting this issue. 

As I mentioned, the first 2 models run as expected, using the current syntax, while the third fails with the following error. 
```
ERROR: MethodError: no method matching rankUpdate!(::LinearAlgebra.Diagonal{Float64,Array{Float64,1}}, ::Array{Float64,2}, ::Float64)
```

**Comment by palday** [comment]
Please remember that minimal working examples should be, well, *minimal*. As you point out, `@eval` isn't relevant for the issue here.

The missing `rankUpdate!` method should already fixed in the current development version, which can be installed from the Pkg REPL:

```julia
julia>]add MixedModels#master
```

**Comment by palday** [comment]
Also, there may be better ways to construct formulae programmatically, but @kleinschmidt would know best.

**Comment by kleinschmidt** [comment]
Yes programmatic creation of formulae should work, please open an issue on StatsModels if it doesn't for you, @liamlundy !

**Comment by liamlundy** [comment]
> Please remember that minimal working examples should be, well, _minimal_. As you point out, `@eval` isn't relevant for the issue here.
> 
> The missing `rankUpdate!` method should already fixed in the current development version, which can be installed from the Pkg REPL:
> 
> ```julia
> julia>]add MixedModels#master
> ```

It sounds like the fix for my issue is in master which is great news. Thank you! I'll close this issue out given that info.

I don't think that an unnecessary `@eval` makes this a non-minimal example. It clearly isn't causing the issue given the context of the full example and doesn't cause problems in the code. Sorry if it caused any confusion to you.

FYI, the `eval` will not automatically expand code unless you are using the interpolation syntax so it would not have an effect on this example either way.

@kleinschmidt I will definitely look into this. I don't anticipate any issues, just haven't gotten around to it. Thanks!
