### ISSUE TITLE
Question on ZeroCorr term / AbstractRandomEffectsTerm

### ISSUE THREAD

**Issue by behinger** [JuliaStats/MixedModels.jl#293]
I have the following problem:
I have a multiple dispatch function with a term-type signature

`term::TimeExpandedTerm{<:RandomEffectsTerm}}`

But `y~1+zerocorr(A|B)`  has the following type:

```julia
unfold.TimeExpandedTerm{MixedModels.ZeroCorr}
```
without any access to the underlying subtype.

Is it possible to change

```julia
struct ZeroCorr <: AbstractTerm
    term::RandomEffectsTerm
end
```
to

```julia
struct ZeroCorr{T<:RandomEffectsTerm} <: AbstractTerm 
    term::T
end
```
Then I think I could do a dispatch like this (I think):

`term::TimeExpandedTerm{<:Union(RandomEffectsTerm,AbstractTerm{<:RandomEffectsTerm}}`

**Alternative**, is it possible to introduce an AbstractRandomEffectsTerm, where the Term ZeroCorr could inherit from? 

**Maybe** it is also possible to put all ZeroCorr definition in one place so that it is easier to understand what is internally happening?

tagging @kleinschmidt

**Comment by palday** [comment]
`AbstractRandomEffectsTerm` is on our list of long-term re-factoring projects.  I think your first suggested approach won't provide quite the behavior you want, but maybe the following would and thus be a decent stopgap:
```julia
term::TimeExpandedTerm{<:Union(RandomEffectsTerm,MixedModels.ZeroCorr)}
```

@kleinschmidt probably has a better overview of that portion of the code though.

**Comment by behinger** [comment]
yeah your fix works for ZeroCorr, but I would like to just "loop-through" types for other e.g. OneCorr (if it would exist), without explicitly stating all of them.

Can you elaborate why it might not work? Seems to work for TimeExpandedTerm

**Comment by palday** [comment]
There are two levels: the `is a ` vs. `has a` trouble from classical OOP, and the parameterization of `AbstractTerm`. For the latter bit: I'm not sure it will always play nice; moreover, you might catch terms you don't want.  I think the better way to handle this is through inheritance, because a zero-correlation term is a random-effects term, but I could see the argument for doing it through encapsulation. (And you could actually do both: have `ZeroCorr` inherit from the abstract class and still be parameterized to encapsulate a concrete type, although that might be considered unholy.)

**Comment by kleinschmidt** [comment]
You could handle this in a slightly more elegant way by defining a trait like

```julia
is_ranef_term(::Type{RandomEffectsTerm}) = Val(true)
is_ranef_term(::Type{ZeroCorrTerm}) = Val(true)
is_ranef_term(::T) where {T} = Val(false)

f(t::T) where {T<:AbstractTerm} = f(t, is_ranef_term(T))
f(t, ::Val{true}) = ... # ranefs here
f(t, ::Val{false}) = ... # everything else
```

but I'm not sure whether that's any better.

I agree that making `ZeroCorr <: AbstractRanefTerm` is long-term the better thing to do.

**Comment by palday** [comment]
@dmbates is this (`AbstractReTerm`) another abstraction we should add? So then

```julia
abstract struct AbstractReTerm end

struct ZeroCorr <: AbstractReTerm
    term::RandomEffectsTerm
end

struct ReTerm <: AbstractReTerm
# all the ReTerm stuff
end
```
