### ISSUE TITLE
PosDefException error while fitting a model

### ISSUE THREAD

**Issue by yuexiao-marketingattribution** [JuliaStats/MixedModels.jl#313]
We don't run into this very often but it happens.  While fitting a model with RE we saw this error.  

> ERROR: PosDefException: matrix is not positive definite; Cholesky factorization failed.
> 10:39:03 AM
> error
> Julia exception: PosDefException: matrix is not positive definite; Cholesky factorization failed.
> Stacktrace:
>  [1] cholUnblocked!(::Array{Float64,2}, ::Type{Val{:L}}) at /root/.julia/packages/MixedModels/YIBOE/src/linalg/cholUnblocked.jl:29
>  [2] updateL!(::MixedModels.LinearMixedModel{Float64}) at /root/.julia/packages/MixedModels/YIBOE/src/pls.jl:151
>  [3] #fit!#16(::Bool, ::Nothing, ::Function, ::MixedModels.LinearMixedModel{Float64}) at /root/.julia/packages/MixedModels/YIBOE/src/pls.jl:205
>  [4] fit! at /root/.julia/packages/MixedModels/YIBOE/src/pls.jl:174 [inlined]

I went back to the data and realized that some variables have relatively big values.  When I divide the value of a few variables by 1,000,000, I got the model ran successfully.  I know large values in independent variables could produce problems.  What we have in this case is numbers that go from negative millions to positive millions.  Is this something we should always watch out for in the data we model?  We don't seem to have problems to run FE on the variable but of course it involves completely different estimation process.

**Comment by palday** [comment]
For data with such a large range, it's usually recommended to center and scale (i.e. subtract the mean and then divide by the standard deviation), even outside of a mixed-models context. This has some motivation in interpretation, but it's particularly useful for estimation if all the variables are on the same scale, because it makes life easier for the optimizer.

**Comment by palday** [comment]
The other time `PosDefException` can occur is for misspecified random-effects which can result in a covariance matrix that isn't positive semi-definite. This is comparable to having a negative variance, which is why it is not valid.
