### ISSUE TITLE
Conflict with the latest version of NLopt v0.6.0 #master

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaStats/MixedModels.jl#315]
Hello!
I have difficulty to add the current master branch of MixedModels.jl due to the conflict with the working version of NLOpt v0.6.0 #master. Currently, that version of NLopt is the only version that works. Previous versions, e.g., v0.5.0 and v0.5.1 do not work under Julia 1.4. So, I added this master branch of NLopt first. Then, I tried to add the MixedModels.jl, but got the following error:
```
(@v1.4) pkg> add MixedModels#master
    Cloning git-repo `https://github.com/JuliaStats/MixedModels.jl.git`
   Updating git-repo `https://github.com/JuliaStats/MixedModels.jl.git`
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package NLopt [76087f3c]:
 NLopt [76087f3c] log:
 ├─possible versions are: 0.6.0 or uninstalled
 ├─restricted to versions 0.5 by MixedModels [ff71e718] — no versions left
 │ └─MixedModels [ff71e718] log:
 │   ├─possible versions are: 2.2.0 or uninstalled
 │   └─MixedModels [ff71e718] is fixed to version 2.2.0
 └─NLopt [76087f3c] is fixed to version 0.6.0
```
Would things work if `Project.toml` of the MixedModels.jl is updated to the NLopt v0.6.0? Currently, it is set as v0.5.0. Thanks for your help!

**Comment by BoundaryValueProblems** [comment]
@palday Thanks a lot! It's working now if I add the master branch!

**Comment by likanzhan** [comment]
I had the following error?

`
(@v1.4) pkg> add MixedModels#master

ERROR: invalid git HEAD (reference 'refs/heads/master' not found)
`

What could be the reason ?

Thanks.
