### ISSUE TITLE
fixef and coef for GLMM

### ISSUE THREAD

**Issue by palday** [JuliaStats/MixedModels.jl#318]
The memory-efficient versions of `fixef!`, `coef`, etc. introduced for LMM in #287 don't yet GLMM methods. Since the new versions also introduced a new way to handle rank-deficiency in extractor methods, we should probably update the GLMM methods. Potentially related is this warning I get when running the testsuite for #317.

```julia
WARNING: Method definition fixef!(AbstractArray{T, 1}, MixedModels.LinearMixedModel{T}) where {T} in module MixedModels at /XXX/MixedModels.jl/src/linearmixedmodel.jl:337 overwritten at /XXX/MixedModels.jl/src/generalizedlinearmixedmodel.jl:281.
```

**Comment by dmbates** [comment]
Any suggestions of an example to test the rank-deficient case or should I just make one up?

**Comment by palday** [comment]
I don't have any suggestions, so I would just make one up!
