### ISSUE TITLE
URLs for Tier 1 and Tier 2 CI checks in README.md

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#342]
Clicking on the Tier 1 or Tier 2 buttons on the README display takes you to the PkgEval page.  I suspect it is because of segments like
```
[![T1-url][T1-img]][pkgeval-url] [![T2-url][T2-img]][pkgeval-url]
```
in the table description but I am not entirely sure what should replace `[pkgeval-url]` in there.  Should those be like `[![][T1-img][T1-url]]` instead?

**Comment by palday** [comment]
Good question, that seems like question for @Nosferican  :)

**Comment by Nosferican** [comment]
I will take a look at it once I get back from the gym.

**Comment by dmbates** [comment]
Are you back from the gym yet, @Nosferican ?  Did you get lost?

**Comment by Nosferican** [comment]
On it... Got caught up on meetings and DARPA challenge tasks. Working on it now.
