### ISSUE TITLE
Failure showing fitted models on julia-1.6.0-DEV.855 and later

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#363]
As I reported in https://github.com/JuliaGraphics/Showoff.jl/issues/24 the re-write of `Printf` in https://github.com/JuliaLang/julia/pull/32859 removed `Base.Grisu`, which has broken the `Showoff` package.

I have felt for a while that the use of `Showoff` is more ornamental than useful so maybe now is the time to bite the bullet and strip the use of `Showoff.showoff` from `MixedModels`.

One fewer dependency sounds like a good idea to me.  Opinions?

**Comment by palday** [comment]
One fewer dependency seems fine with me. Grep'ing the sources, we're only using it in three lines and two of them are essentially the same from a printing perspective (sigmas and variances).

(I wasn't even aware we were using `Showoff`!)

 Without actually trying it out, I would guess we can write a replacement in < 10 lines of code. :grinning:

**Comment by dmbates** [comment]
My recollection is that the Ryu package, which has been part of Julia's stdlib since 1.4, is reasonably accessible.

My sleep schedule is kind of messed up right now so if I find myself awake in the middle of the night I will take a run at it.

**Comment by dmbates** [comment]
It appears that we use `Ryu.writefixed(obj, 4)` for the deviance in the show method for a `GeneralizedLinearMixedModel` so we could probably do the same for the show method for a `LinearMixedModel`.  The `4` is four digits after the decimal point, which is more than enough for those values.  (Recall that changes in the deviance are compared to a chi-square distribution.)

**Comment by dmbates** [comment]
Seems like the changes to Printf have also broken the ProgressMeter code so I am going to punt for the time being on getting MixedModels to work with the development version of Julia.  I did remove the dependency on Showoff in #364 but we probably don't want to commit that to master until after the tutorial this week.
