### ISSUE TITLE
Use of LinearAlgebra.Matrix is flagged as a possible method call error

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#365]
It may be that we should be writing `Array(foo)` instead of `Matrix(foo)` to convert to a dense array.

**Comment by palday** [comment]
I recall that in some of the tests, the default alias used for `Matrix{T}` or `Array{T, 2}` changed between Julia versions, but I don't recall in which direction and between which versions.

**Comment by andreasnoack** [comment]
Where do you see this warning?

**Comment by palday** [comment]
My guess is VSCode -- but in my experience VSCode gives some false positives on this stuff.

**Comment by dmbates** [comment]
Yes, it was in VSCode that I saw the warning.

**Comment by andreasnoack** [comment]
> but in my experience VSCode gives some false positives on this stuff.

Yeah. I've actually ended up disabling the linter in VSCode. I think there were too many false positives for it to be useful.

**Comment by dmbates** [comment]
Thanks for the discussion.  I will close this and ignore the warnings.
