### ISSUE TITLE
Remove dependency on BlockDiagonals

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#366]
Right now an update in the BlockDiagonals package is causing several other packages in the MixedModels dependencies to be downdated.  It turns out that BlockDiagonals is used in exactly one place so it should be straightforward to eliminate that dependency.

**Comment by palday** [comment]
Can you point me to the spot where BlockDiagonals is being used?

**Comment by dmbates** [comment]
In `src/remat.jl` the definition of `_amalgamate` calls `BlockDiagonal(...`

**Comment by dmbates** [comment]
One thing I don't like about the show method eventually called on the object returned by `StatsModels.lrtest` is that it doesn't describe the models.  It is like
```julia
julia> lrtest(bigmodel, model, nullmodel)
  Likelihood-ratio test: 3 models fitted on 12 observations
  ──────────────────────────────────────────────
       DOF  ΔDOF  Deviance  ΔDeviance  p(>Chisq)
  ──────────────────────────────────────────────
  [1]    4         14.0571                      
  [2]    2    -2   15.9559     1.8988     0.3870
  [3]    1    -1   16.3006     0.3447     0.5571
  ──────────────────────────────────────────────
```
which is not quite as informative as I would like.
