### ISSUE TITLE
Add dependency on DataAPI and change levs to levels

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#383]
I think it would generally be a good idea to add a dependency on `DataAPI.jl` just to get access to certain standardized names and docstrings.  Currently the function to extract the levels of an `ReMat` is called `levs` but it really should be `levels` for consistency with other packages.

**Comment by dmbates** [comment]
@palday, @kleinschmidt, @Nosferican Any opinions on this?  I can do it if the general opinion is that this is a good idea.

**Comment by palday** [comment]
I'm fine with this, esp since `DataAPI.jl` has an explicit policy of basically "only stubs", so there's no real impact on the compile times. Are there other places where we need to align (or make our divergence explicit)?
