### ISSUE TITLE
Testing on julia-v1.6.0-DEV

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#387]
Our testing on Future and testing using a locally compiled `Version 1.6.0-DEV.1062 (2020-09-26)` are failing.  I am getting 
```
signal (11): Segmentation fault
in expression starting at /home/bates/.julia/dev/MixedModels/test/UniformBlockDiagonal.jl:10
```
with the apparent problem when trying to compile
```
materialize at ./broadcast.jl:837 [inlined]
_ranef_refs at /home/bates/.julia/dev/MixedModels/src/randomeffectsterm.jl:103
```
I think that alpha test versions of 1.6.0 are due within the next few weeks.  I am happy to just keep a watch on this until then but once the test versions start coming out we will need to dig deeper into what is going on.

**Comment by dmbates** [comment]
Ah, I believe this is due to having assertions on and the problem with compiling https:github.com/JuliaData/CategoricalArrays.jl  It may go away after we fix #381

**Comment by palday** [comment]
Did this get better with #381 and #382?

**Comment by dmbates** [comment]
See #402
