### ISSUE TITLE
Bootstrap and simulate don't resample weights

### ISSUE THREAD

**Issue by palday** [JuliaStats/MixedModels.jl#466]
This is true for LMM and GLMM

**Comment by palday** [comment]
I'm not sure this is actually an issue: the weights are in some sense just treated as invariant across stimulations, so if you want to simulate something else, you should just change the weights. I guess we could add a `wts` kwarg, but I'm not sure it's worthwhile until someone requests it.

**Comment by DarioSarra** [comment]
Personally, I would use this feature. Plotting the bootstrap data against the original dataset is a common way to visually confirm the goodness of the model in biological science.

**Comment by palday** [comment]
But in that case, the weights don't change -- which is what's happening right now. If the weights should change with each bootstrap iteration, then the question becomes "what does it mean to bootstrap weights?". I'm not sure that's well defined for the parametric bootstrap because there is no distributional assumption assigned to the weights.

**Comment by DarioSarra** [comment]
Right, ideally the weights should not change. My bad I misunderstood the issue as if bootstrap was not using the weights at all.

**Comment by palday** [comment]
I made the title somewhat clearer.

**Comment by palday** [comment]
I'm closing this because I can't think of a good way to simulate weights within the parametric bootstrap framework. There is no assumption about the weights distribution; moreover, they are in some sense one of the parameters that make it "parametric" (e.g., they are a parameter to the Binomial distribution). 

If we have a compelling use case and a clear idea of how the weights should be resampled, then I'm happy to revisit.
