### ISSUE TITLE
isnested assumes that grouping terms have single blocking vars

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaStats/MixedModels.jl#471]
Checking `isnested` for two models where at least one of them has an interaction
blocking variable (e.g., `(1 | batch & cask)`) fails because the interaction
term does not have a `.sym` field.  Should use the `fname` function for this
instead (I'll file a fix).

**Comment by palday** [comment]
Thanks!

Do it against `master`/`4.0-dev` and I'll backport to 3.x

Note also that `isnested` will return some false positives for certain fancy structures (e.g. the compound symmetric model formulated as two scalar random effects), which is part of why we have the non-exported `likelihoodratiotest` which does less stringent checking and just assumes you know what you're doing.
