### ISSUE TITLE
Be Diagonal where you can

### ISSUE THREAD

**Issue by palday** [JuliaStats/MixedModels.jl#487]
We should allow the λ field in an `ReMat` in the `MixedModels` package to be `LowerTriangular{T,Union{Diagonal{T},Matrix{T}}}` and check if the `inds` make the result diagonal.  For example, `zerocorr` applied to an `ReTerm` results in a diagonal λ.  A surprisingly large amount of the time in `updateL!` is spent in the mulitplications by Λ, especially for a `UniformBlockDiagonal` (1, 1) block.

_Originally posted by @dmbates in https://github.com/RePsychLing/MixedModelsSim.jl/pull/42#issuecomment-801161864_

**Comment by dmbates** [comment]
Thanks for making this into an issue.
