### ISSUE TITLE
Likelihood ratio test to compare `Linear[Mixed]Model`

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaStats/MixedModels.jl#491]
Likelihood ratio tests can be used to assess the suitability of random effects terms, but it's currently not possible to directly compare a `LinearModel` and a `LinearMixedModel` to assess the suitability of no random effects vs. some random effects.  This would require adding methods to determine whether a `LinearModel` is nested within a `LinearMixedModel` and maybe a specialized test method to make sure you're getting the right likelihood value (e.g. can't use the deviance since the baseline is different for the two).

**Comment by palday** [comment]
@dmbates Do you have any philosophical objections to this? Practically, the biggest thing is that we need to look at the log likelihoods directly and not the deviances (`LinearModel` takes the additive constant for the saturated model into account unlike `LinearMixedModel`).

**Comment by dmbates** [comment]
Nope.  No philosophical objections.
