### ISSUE TITLE
ranef(; named=true) doesn't work for GeneralizedLinearMixedModel

### ISSUE THREAD

**Issue by stefanjwojcik** [JuliaStats/MixedModels.jl#499]
I love this package, kudos to you all for writing such a great addition to the Julia community. 

Here is my issue. After fitting a GLMM, the `ranef()` doesn't work as expected with the `named=true` argument, and it seems that this functionality should work for this kind of model. For context, I found it works as expected for a simple LMM. 

Here is reproducible code:
`df = DataFrame(y = rand([0,1], 1000), mycat = rand(["hey", "this", "test"], 1000))`

`mod = fit!(GeneralizedLinearMixedModel(@formula(y ~ (1|mycat)), df, Bernoulli() ), fast=true)`

`ranef(mod; named=true)`

Error: 
`MethodError: no method matching ranef(::GeneralizedLinearMixedModel{Float64}; named=true)`

**Comment by palday** [comment]
`named=true` isn't supported in MixedModels 3.x, though there is a lingering documentation error.  Use `raneftables` instead.
