### ISSUE TITLE
Save and restore an OptSummary

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#505]
When fitting large, complex models, especially within a Pluto.jl notebook, the user can be delayed considerably by the sheer time that it takes to fit the model.  When you save a Pluto notebook it doesn't save the results - just the code to generate the results and descriptions.

For a linear mixed-effects model the results can be regenerated from the data table, the formula, the contrasts and the final value of the θ parameter.  I would save the data table as an `.arrow` file.  I am open to suggestions of the best way to preserve the formula and contrasts (looking at you @kleinschmidt ).  Instead of just saving the value of θ, I would save (almost) the entire `OptSummary` object, probably as a `.json` file. (Again, I am open to suggestions for alternative formats.)

I say `(almost) the entire ...` because in its current form the `lowerbd` field can't be expressed in JSON in most cases because the unbounded parameters have `-Inf` in those positions and JSON doesn't allow non-finite values, even for floating point.

So, modulo the problem of the `lowerbd` field, it appears that one can add a dependency on `StructTypes` and specify the `StructType` for `::Type{<:OptSummary}` to be `StructTypes.Mutable()` and specifying `StrucTypes.excludes()` for the `lowerbd` field.

To restore the contents I plan to read the JSON file without specifying the struct.  This returns a JSON3.Object with propertynames corresponding to the fieldnames - minus `lowerbd`.  I'll just use this to overwrite the fields in the model's optsum field.

**Comment by kleinschmidt** [comment]
Honestly for that kind of application I'd just `serialize` the formula (after `apply_schema`).  Or use JLD2.  The structs are not that complicated but will depend on the package/julia versions.

**Comment by palday** [comment]
If we need a stable format for JSON / Arrow serialization, then I would just serialize the string representation of a formula.
