### ISSUE TITLE
Variance and or correlation structures

### ISSUE THREAD

**Issue by mmeierer** [JuliaStats/MixedModels.jl#51]
Allow for additional variance and or correlation structures in the conditional distribution of the response comparable to the `nlme package` in `R`

**Comment by dmbates** [comment]
I regret to say that this is not high on my priority list, although pull requests are welcome.

**Comment by Nosferican** [comment]
Got some recommended references or suggestions for the implementation?

**Comment by PharmCat** [comment]
Hello! Can you kindly answer to my following question.
In equation 6 used this decomposition:
```
LL′=Λ′Z′ZΛ+I
```
How REML estimation can be done if I not a identity matrix and replaced by R - q x q matrix with known structure, for example:  
```
R:
σ²₁ 0
0   σ²₂
```

**Comment by palday** [comment]
@PharmCat Where would that R matrix come from? The decomposition that gets you to that point depends on the spherical random effects, so if your R is just a diagonal covariance matrix from the normal distribution, then this has already been factored out at this point. The constraints on the variance structure arise in the form of Λ used to transform the spherical random effects, as seen in [`zerocorr!`](https://github.com/dmbates/MixedModels.jl/blob/1745530694b13b27807c80d1dd10c8fb90edc807/src/remat.jl#L437-L445).

Also, if you look at the the `MixedModels.jl` source code, you'll see that the [REML estimate](https://github.com/dmbates/MixedModels.jl/blob/1745530694b13b27807c80d1dd10c8fb90edc807/src/linearmixedmodel.jl#L408-L411) arises from [the way the residual degrees of freedom are computed](https://github.com/dmbates/MixedModels.jl/blob/1745530694b13b27807c80d1dd10c8fb90edc807/src/linearmixedmodel.jl#L196-L199). This doesn't impact the derivation of the profiled log likelihood, but does change the objective function in a way that it's no longer a proper likelihood and is dependent on the fixed-effects parameterization.

**Comment by PharmCat** [comment]
> 
> 
> @PharmCat Where would that R matrix come from? The decomposition that gets you to that point depends on the spherical random effects, so if your R is just a diagonal covariance matrix from the normal distribution, then this has already been factored out at this point. The constraints on the variance structure arise in the form of Λ used to transform the spherical random effects, as seen in [`zerocorr!`](https://github.com/dmbates/MixedModels.jl/blob/1745530694b13b27807c80d1dd10c8fb90edc807/src/remat.jl#L437-L445).
> 
> Also, if you look at the the `MixedModels.jl` source code, you'll see that the [REML estimate](https://github.com/dmbates/MixedModels.jl/blob/1745530694b13b27807c80d1dd10c8fb90edc807/src/linearmixedmodel.jl#L408-L411) arises from [the way the residual degrees of freedom are computed](https://github.com/dmbates/MixedModels.jl/blob/1745530694b13b27807c80d1dd10c8fb90edc807/src/linearmixedmodel.jl#L196-L199). This doesn't impact the derivation of the profiled log likelihood, but does change the objective function in a way that it's no longer a proper likelihood and is dependent on the fixed-effects parameterization.

I try to understand how REML is computed via [documentation](https://dmbates.github.io/MixedModels.jl/latest/optimization/#The-probability-model-1) and match it with mixed model REML solution described [here](https://www.jstor.org/stable/2529876?origin=JSTOR-pdf)  where V = ZGZ'+R (SAS like notation). If structured R used instead σ²I how would REML eqation changed?

**Comment by palday** [comment]
The methods and representations used in MixedModels don't map directly onto the equations in that paper -- indeed, that's the use of a sparse representation is the major innovation in MixedModels. There is no 'structured R' at that point in the representation in MixedModels because the restrictions in the variance structures would be represented in the form of the Cholesky factor used to get to the spherical random effects. I linked to the specific points in the code where the REML computation differs from the ML computation, namely in a penalty for the dimension of the fixed-effects matrix.

**Comment by PharmCat** [comment]
@palday Thank you for the clarification!
