### ISSUE TITLE
Storage of Parameter Vector for GLMM Bootstrap

### ISSUE THREAD

**Issue by palday** [JuliaStats/MixedModels.jl#517]
Right now, we store whatever vector we used for optimization, whether that's "just" theta or the concatenated beta-theta vector. I think we should probably store just the theta vector because we already store beta separately *and* `issingular(::MixedModelsFitCollection)` assumes the pure theta vector in its `lowerbd` check.

Thoughts @dmbates ?

**Comment by dmbates** [comment]
Seems reasonable.
