### ISSUE TITLE
Incorrect fact in description of Normalized Gauss-Hermite quadrature

### ISSUE THREAD

**Issue by tompdavis** [JuliaStats/MixedModels.jl#525]
In the comments for Normalized Gauss-Hermite quadrature, it says "More formally, a kth order rule is exact when `f(x)` is a `k-1` order polynomial."  However, the technique is in fact exact when `f(x)` is a polynomial of order `2k-1` or less.   This is on the wiki https://en.wikipedia.org/wiki/Gaussian_quadrature.  

To understand this, just think about polynomial division.  If `f(x)` is of order `2k-1`, then you can write 

`f(x) = H_k(x)q(x) + r(x)`

where the quotient `q(x)` and remainder `r(x)` polynomials are of order `k-1`.  The first term vanished because the technique uses the roots of `H_k(x)` as the abscissa, and `r(x)` is of order `k-1`, hence given exactly explicitly by the quadrature method.

**Comment by dmbates** [comment]
Thank you for pointing that out.  I will make that change.
