### ISSUE TITLE
Adjustments for julia-v1.7.0

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#532]
When the workaround for https://github.com/JuliaLang/julia/issues/40048 is merged we can start testing on julia-v1.7.0-DEV

In `test/runtests.jl` we should replace the call to determine the BLAS in use with `BLAS.get_config()` for v1.7.0-DEV

A couple of instances of `qr(x, Val(true))` need to be replaced by `qr(x, ColumnNorm())` for recent versions of v1.7.0-DEV.

**Comment by palday** [comment]
I had already started tinkering with this locally. :smile: I'll take care of it.

If 1.6 really does become the next LTS, then we should support it until we absolutely need some killer feature from a point release, but I think we can start wrapping some of the incremental improvement and the like in`@static` to make it really obvious what we can cut when we drop support for 1.6. 

On a related note: should we drop all pre 1.6 support with the 4.0 release?

**Comment by dmbates** [comment]
Thanks for volunteering.

I feel that we should drop all pre 1.6 support if and when it becomes the LTS release.
