### ISSUE TITLE
`_zerocorr!` methods in src/linearmixedmodel.jl seem vestigial 

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#546]
What say you, @palday ?  Can these methods be removed?  I happened to be looking at test coverage and noticed that they are not called in any tests - then I searched for the name and it only occurs in those definitions.

By the way, the VS Code command `Tasks: Run Test Task` combined with the `Coverage Gutters` extension does a nice job of showing up your test coverage without generating a raft of extra files.

**Comment by palday** [comment]
They are basically vestigial. I wanted to use them as a starting point for #409, but have no objection to them being removed.

**Comment by palday** [comment]
Closed by #547
