### ISSUE TITLE
Add `fitlog` kwarg for logging the parameter vector during optimization

### ISSUE THREAD

**Issue by palday** [JuliaStats/MixedModels.jl#549]
As discussed in [some visualization work](https://github.com/RePsychLing/SMLP2021/pull/14#issuecomment-897900060), we should add a `fitlog=nothing` kwarg to the `fit` and `fit!` methods. In the default case, nothing changes. In the case that `fitlog` is a collection supporting `push!`, then we `push!(fitlog, SVector{length(val)}(val)` in the `obj` function being optimized.

**Comment by dmbates** [comment]
One approach, which, unfortunately, would be an incompatible change in an underlying struct, would be to change the `optinfo` fields to have `initial` and `final` replaced by, say, a Vector{StaticVector{T,npar}} perhaps called `parameters`.  The convention would be that what is now `initial` would become `first(parameters)` and what is now `final` would become `last(parameters)`.  An optional integer-valued argument to `fit`, with a name reflecting the `thinning` of the parameter log, would indicate how frequently parameter vectors and objective values were to be pushed onto the vector of parameters and an accompanying vector of objective values.  The default, 0, would indicate that only the initial and final values are to be pushed onto the vector.  The condition in the objective function evaluation on whether to push would be like
```julia
    !iszero(thin) && iszero(rem(iter, thin))
``` 

I regret that it seems that the way to stimulate my thinking about incompatible changes is to release a new version of the package.

**Comment by palday** [comment]
We can have it both ways -- we can introduce `fitlog` for now and when we've accumulated a few other breaking changes, do your suggestion for 5.0. I've been thinking about reworking `OptSummary` anyway so that we access NLopt through the JuMP interface. That would make it easier in the future to look at other optimizers.

**Comment by dmbates** [comment]
Sounds like a plan.  What do you think of using a `thin`-type of argument instead of a yes/no for the logging to save, e.g., every 10th parameter vector?

**Comment by palday** [comment]
I like the idea of adding a `thin` argument. We're rapidly approaching an MCMC-like approach to this :wink:
