### ISSUE TITLE
Identifiablity compared to lmer

### ISSUE THREAD

**Issue by spooseh** [JuliaStats/MixedModels.jl#550]
When the number of random effects is smaller than the number of observations, `lmer` (v1.1.23) exits with an error message complaining that 
```R
Error: ... ;the random-effects parameters and the residual variance (or scale parameter) are probably unidentifiable
```
but in Julia `MixedModels.fit()` (v3.8.0) continues normally. Has the identifiability concern been resolved in MixedModels.jl?

**Comment by palday** [comment]
> When the number of random effects is smaller than the number of observations

I don't understand this -- generally having as many random effects as observations is the problematic case.

But in more general terms: MixedModels.jl doesn't do as much warning as lme4. It's up to the user to make sure that the model they specify makes sense and that they have sufficient data to estimate that model.

**Comment by dmbates** [comment]
Because the conditional means (or conditional modes, in the case of a GLMM), sometimes called the BLUPs, are the solution to a penalized least squares problem they can be evaluated even when the number of random effects exceeds the number of observations.  Whether or not they will be meaningful is another matter.  As @palday has said, MixedModels.jl doesn't do as much warning as lme4.

**Comment by spooseh** [comment]
@palday and  @dmbates: thanks for your input . I hope after @dmbates' answer it's clear what I meant by the number of random effects. For the record, given
```Julia
sleepstudy = MixedModels.dataset(:sleepstudy)
fm = fit(MixedModel, @formula(reaction ~ 1 + days + (1 + days|subj)), sleepstudy)
```
`ranef(fm)[1]` is a 2x18 matrix and hence 38 BLUPs in total.

**Comment by dmbates** [comment]
The terminology gets a little tricky here.  BLUPs refers to the random effects, which are not parameters in the model.  They are unobserved random variables.  Even though  the linear predictor expression seems to treat the random effects and the fixed-effects parameters similarly, their roles in the probability model is very different.  There are 2 fixed-effects parameters and 36 random effects (which are not technically parameters) in this model.
