### ISSUE TITLE
WARNING: `both GLM and Distributions export "Normal"; uses of it in module MixedModels must be qualified

### ISSUE THREAD

**Issue by likanzhan** [JuliaStats/MixedModels.jl#587]
- The printed error information

<img width="814" alt="Screen Shot 2021-12-29 at 12 06 39 PM" src="https://user-images.githubusercontent.com/10531698/147626557-d98f4f72-61e9-4c12-a27b-158ff085eeb2.png">

- The possible location triggering the error

<img width="730" alt="Screen Shot 2021-12-29 at 12 06 33 PM" src="https://user-images.githubusercontent.com/10531698/147626590-9119a96b-f6a8-4adb-bb04-78057d10c477.png">

- MixedModels.jl information
```julia
  [ff71e718] MixedModels v4.5.0
```

- System information

```julia
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, westmere)
Environment:
  JULIA_NUM_THREADS = 1
  JULIA_EDITOR = code
  JULIA_PKG_SERVER = https://mirrors.bfsu.edu.cn/julia/static

```

**Comment by palday** [comment]
Can you give us the output of
```julia
julia> using Pkg; Pkg.status()
```

? 

GLM.jl does export `Normal`, but it's a re-export of `Normal` from Distributions.jl., so I'm not yet sure what's going wrong here.

**Comment by likanzhan** [comment]
<img width="605" alt="Screen Shot 2021-12-30 at 9 16 35 AM" src="https://user-images.githubusercontent.com/10531698/147714148-6254328a-a0f1-43e6-ba89-843fe7ac3bd5.png">
@palday

**Comment by palday** [comment]
This is really weird, both [Distributions](https://github.com/JuliaStats/Distributions.jl/blame/master/src/Distributions.jl#L142) and [GLM](https://github.com/JuliaStats/GLM.jl/blame/master/src/GLM.jl#L32) haven't changed the relevant exports in several years.

What happens if you `update` and `resolve` again?

**Comment by likanzhan** [comment]
I reinstalled the package, the problem disappears. Sorry for the confusion.

**Comment by palday** [comment]
@likanzhan No worries! It was an interesting puzzle and it's great to have dedicated users. :smile:
