### ISSUE TITLE
Export StatsModels.AbstractContrasts from MixedModels.jl

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#589]
So that a `contrasts` dictionary can be initialized as
```jl
const contrasts = Dict{Symbol, AbstractContrast}()
```
and individual contrasts can simply be assigned to this const Dict.

**Comment by palday** [comment]
In our `constrast` kwargs, we use `Dict{Symbol, Any}()` as the the default value.

**Comment by dmbates** [comment]
Should we change the default then?  I can't think of a case where the value would not be an `AbstractContrast`  but I would defer to you and @kleinschmidt on this.

**Comment by palday** [comment]
@kleinschmidt is definitely the one who knows the Correct Answer here

**Comment by kleinschmidt** [comment]
I don't think the type restriction would be adding anything, and if the default is already Any then it's  probably not  necessary on StatsModels side either.

**Comment by dmbates** [comment]
Okay, thanks for the comments.
