### ISSUE TITLE
export StatsModels.AbstractContrasts

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#620]
I have gravitated to defining a global `contrasts` dictionary for which the value type should be `StatsModels.AbstractContrast` (or `Any`) to allow for both `Grouping` "contrasts" and various encodings of categorical fixed-effects covariates.

At present this requires either `using` or `import` of StatsModels or a peculiar construction like
```julia
const contrasts = Dict{Symbol, MixedModels.StatsModels.AbstractContrasts}()
```

Is it worthwhile exporting `StatsModels.AbstractContrasts` from `MixedModels` or am I overthinking this?

**Comment by dmbates** [comment]
Actually I found out that standardizing transformations like `Center` in `StandardizedPredictors` are not `AbstractContrasts` so the question is moot.  I am, for the time being, defining the contrasts as
```
const contrasts = Dict{Symbol,Any}();
```

**Comment by kleinschmidt** [comment]
Yeah the "contrasts" get passed to the "hints" argument in concrete term so they can be any number of things (you can use like `ContinuousTerm` for instance IIRC)
