### ISSUE TITLE
Predict: only one level found

### ISSUE THREAD

**Issue by jariji** [JuliaStats/MixedModels.jl#625]
I wanted to `predict` a few values, but it said

```jl
julia> MixedModels.predict(fitval, d)
ERROR: ArgumentError: only one level found: 2016 (need at least two to compute contrasts).
```

My goal is to compute the prediction for one level, so I don't want to pass two levels.

**Comment by palday** [comment]
Internally a [new model is constructed to simplify the bookkeeping][1] and model construction relies on the general machinery for constructing model matrices, which then requires being able to compute the contrasts. We avoid this constraint in Effects.jl, but also don't worry about the random effects when computing those effects. We plan to relax this constraint in the future.

In the meantime, the easiest thing to do is include extra observations with the other levels in the call to `predict` and drop them afterwards.

Note that you don't usually need to specify `MixedModels.predict`: `predict` is exported.

[1]: https://juliastats.org/MixedModels.jl/stable/api/#StatsAPI.predict-Tuple%7BLinearMixedModel,%20NamedTuple%7Bnames,%20T%7D%20where%20%7BN,%20D,%20names,%20T%3C:Tuple%7BVararg%7BAbstractArray%7BS,%20D%7D%20where%20S,%20N%7D%7D%7D%7D

**Comment by palday** [comment]
@jariji With the help from @kleinschmidt I've found a simple fix for this error, which we should be releasing shortly (see #653).
