### ISSUE TITLE
Failures in threaded_replicate test

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#640]
I am pretty consistently getting about a 50% failure rate on that test.  @palday Do you also get failures on that?  If so, can we suppress it until we find out why it is failing?

**Comment by palday** [comment]
That test does occasionally fail for me, but almost never nowadays. (An earlier version of the test was a little bit too strict and failed a fair amount.) 

- Which Julia version? 
- Which BLAS? If OpenBLAS, which build? (This is displayed at the start of the testsuite.)
- How many threads do you run Julia with?
- What's your precise CPU architecture? (Trying to figure out which SIMD instructions are available)

I suspect there's an interaction between threading and SIMD that can fail in certain configurations.
