### ISSUE TITLE
Hosmer-Lemeshow test in GLMM (binomial family)

### ISSUE THREAD

**Issue by CamilaDeu** [JuliaStats/MixedModels.jl#699]
Hi, I ran a model using the lme4 package and wanted to know if it is appropriate to apply the Hosmer-Lemeshow test to evaluate the model fit. Thank you!

library(lme4)

#GLMM
m1 <- glmer(Canto ~ T + H + Patm + V + Pp + CU + (1|Evento), data = Datos, family = binomial)

**Comment by palday** [comment]
This question was answered on [r-sig-mixed-models](https://stat.ethz.ch/pipermail/r-sig-mixed-models/2023q3/030450.html). 

I don't know of a Julia implementation of this test.
