### ISSUE TITLE
The ftol_rel should be a small number, not a large number, right?

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#713]
https://github.com/JuliaStats/MixedModels.jl/blob/9ee4a0a9f371eddf9aa68118d96c8a006f4a4d58/src/bootstrap.jl#L183

Should the new value of `ftol_rel` be `1e-8`, not `1e08`?

**Comment by palday** [comment]
Oh that's a bad typo indeed - it should be a small number!
