### ISSUE TITLE
Parametric bootstrapping for hypothesis testing

### ISSUE THREAD

**Issue by joseah** [JuliaStats/MixedModels.jl#716]
Dear MixedModels team,

I was reading the [Parametric bootstrap for mixed-effects models](https://juliastats.org/MixedModels.jl/dev/bootstrap/#Parametric-bootstrap-for-mixed-effects-models) documentation and was wondering if there's any implementation to perform hypothesis testing between a null and full model via parametric bootstrapping (as an alternative for using a LRT).

Cheers,
Jose

**Comment by palday** [comment]
You can bootstrap the null distribution for an LRT, but otherwise the associated hypothesis test for a bootstrap would generally be whether the 95% of the bootstrapped uncertainty interval includes the null value (usually 0).

**Comment by joseah** [comment]
Thanks @palday !
