### ISSUE TITLE
Can @debug calls be removed from the release version

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#732]
@palday There are calls to the `@debug` macro in `grouping.jl` and `Xymat.jl`.  Can those be removed?  I wanted to add some `@debug` calls to, well, debug a situation and found that I ended up with more output than I was expecting.

**Comment by palday** [comment]
Yes, go ahead and drop those -- I think the (auto)grouping code has survived enough usage at this point that we can be fairly confident in it. 😄
