### ISSUE TITLE
restoreoptsum fails after change in JSON file structure in 4.25.0

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/MixedModels.jl#774]
One of the first checks in `restoreoptsum` is on the keys in the dictionary created from the JSON file.  If the optsum JSON file was created with a version prior to 4.25 attempts to restore this optsum under 4.25.0 will fail, with a somewhat misleading error message.  I will split the checks into two parts, one on the fields and one on the lower bounds and allow for patching pre-4.25 saved optsums to the 4.25 names.

**Comment by palday** [comment]
AH, I was wondering why I was having so many problems with previously working code when trying to render EmbraceUncertainty....

**Comment by dmbates** [comment]
I should have a PR ready shortly.
