### ISSUE TITLE
What is current best practice for saving a GLMM?

### ISSUE THREAD

**Issue by dhalpern** [JuliaStats/MixedModels.jl#790]
It seems that saveoptsum/restoreoptsum! only works for linear models. Is there a current solution for saving the fit of a GLMM? Thanks!

**Comment by palday** [comment]
#791 adds GLMM methods to `saveoptsum` and `restoreoptsum!`. I'll try to get it merged this week, but my co-authors are also quite busy and may not have time to review.

**Comment by dhalpern** [comment]
great, thanks so much!
